POST http://localhost:3333/videos
Content-type: application/json

{
    "title": "Video node",
    "description": "Esse é o vídeo 01",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/c3dfb859-2d07-4bda-93f2-953af5bf0194
Content-type: application/json

{
    "title": "Video 01",
    "description": "Esse é o vídeo teste",
    "duration": 90
}

###

DELETE http://localhost:3333/videos/c3dfb859-2d07-4bda-93f2-953af5bf0194