POST https://estudos-nodejs.onrender.com/videos
Content-type: application/json

{
    "title": "Video node",
    "description": "Esse é o vídeo 01",
    "duration": 180
}

###

GET https://estudos-nodejs.onrender.com/videos

###

PUT https://estudos-nodejs.onrender.com/videos/949034e0-1c75-4b48-b9a4-c13d9c5ea47a
Content-type: application/json

{
    "title": "Video 01",
    "description": "Esse é o vídeo teste",
    "duration": 90
}

###

DELETE https://estudos-nodejs.onrender.com/videos/949034e0-1c75-4b48-b9a4-c13d9c5ea47a